config/routes.rb
WdiGroupProject::Application.routes.draw do

  devise_for :users
  resources :users
  root to: "clips#index"

  resources :clips, except: [:update, :edit] do
    resources :comments#, except: [:index, :show]
  end

  post '/clips/update/:id', to: 'clips#like_clicked'
  patch '/clips/:clip_id/playlist/:id', to: 'clips#add_to_playlist'
  post '/clips/playlist/:id', to: 'clips#add_playlist'
  get '/map', to: 'clips#map_clips'


  post '/search', to: 'search#create'

  post '/clips/:id', to: 'clips#snippet'
  get '/clips/:id/snippets', to: 'clips#snippets'

  resources :playlists



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :clip
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  def index
    @clip = Clip.find(params[:clip_id])
    @comments = @clip.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    clip_id = params[:clip_id]
    comment_params = params.require(:comment).permit(:body)
    comment_params[:user_id] = current_user.id
    comment = Comment.create(comment_params)
    comment.clip = Clip.find(clip_id)
    comment.save
    redirect_to clip_path(clip_id)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_new_comment.html.erb
<%= form_for [@clip, @comment] do |c| %>
    <%= c.text_area :body, class: "form-control input-md" %>

    <%= c.submit "comment", class: "btn btn-default" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<div class ="index">
<h3>See all comments for <%= link_to @clip.title, clip_path(@clip) %></h3>

<% @comments.each do |comment| %>
 <h4><li><%= comment.body %></li></h4>

<% end %>
</div>

app/views/comments/new.html.erb
<h3>Enter your comment here</h3>

<%= form_for @comment, url: clip_comments_path do |c| %>
    <%= c.label "Your comment" %>
    <%= c.text_field :body %>

    <%= c.submit %>
<% end %>