config/routes.rb
WdiGroupProject::Application.routes.draw do

  devise_for :users
  resources :users
  root to: "clips#index"

  resources :clips, except: [:update, :edit] do
    resources :comments#, except: [:index, :show]
  end

  post '/clips/update/:id', to: 'clips#like_clicked'
  patch '/clips/:clip_id/playlist/:id', to: 'clips#add_to_playlist'
  post '/clips/playlist/:id', to: 'clips#add_playlist'
  get '/map', to: 'clips#map_clips'


  post '/search', to: 'search#create'

  post '/clips/:id', to: 'clips#snippet'
  get '/clips/:id/snippets', to: 'clips#snippets'

  resources :playlists



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :clips
  has_many :comments
  has_many :playlists
  has_many :likes

  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    },
    :storage => :s3,
    :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME'],
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  },
    :s3_host_name => 's3-us-west-2.amazonaws.com',
    :url => "/system/:hash.:extension",
    :hash_secret => ENV['IMG_KEY']
}

   # Validate content type
  validates_attachment_content_type :avatar, :content_type => /\Aimage/
  # Validate filename
  validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/]


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable #, :confirmable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
    # @user.clip = current_user
    #@user_clips = current_user.clips
  	# @user.send_confirmation_instructions
  end

  def edit
  	@user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(@user)
    end
  end

  def update
  	@user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to action: :show
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :avatar, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="index">
  <%= image_tag @user.avatar.url(:medium) %><br>   
  <%= form_for @user do |u| %>
    <div class="avatar">
      <%= u.file_field :avatar %>
    </div>
    <div class="submit">
      <%= u.submit %>
    </div>
      Email: <%= u.text_field :email, placeholder: "enter email" %> <br>
  <% end %>
</div>



 

app/views/users/show.html.erb
<ul><div class="index">
  <div class="avatar">
  <h2>Welcome!</h2>
  <%= image_tag @user.avatar.url(:medium) %><br>
  <%= @user.email %><br>
  <% if current_user == @user %>
    <%= link_to "Edit Profile", edit_user_path(current_user) %><br>
  <% end %>
  </div>
</div></ul>
<br>

<ol><div class="index"><center><h3>Clips:</h3></center></div></ol>

<% @user.clips.each do |clip| %>
    <!-- Only display if correct user is logged in or if clip is not private -->
    <% if current_user == @user || clip.is_private? != true %>
      <ol>

        <% if clip.snippable_id.nil? %>
          <!-- |clip| media and information -->
          <div class="index clip hoverable" >
            <h4><%= link_to clip.title, clip_path(clip.id) %></h4>
            <!-- if |clip| is a snippet whose parent clip belongs to another user -->
            <% if clip.snippable_id && Clip.find(clip.snippable_id).user_id != @user.id %>
                <h4>Original clip: <a href="<%=clip_path(@clip.snippable_id)%>"><%=Clip.find(@clip.snippable_id).title%></a>
                </h4>
            <% end %>

            by: <%= clip.performer %></br>
            <audio id="track" controls src="<%=clip.mp3.url%>"></audio></br>
            <%= clip.description %> </br>
        <% unless clip.clips.empty? %>
        <p style="text-align:right">+</p>
        <% end %>
          </div>
        <% end %>

        <!-- Snippets -->
        <% unless clip.clips.empty? %>
          <!-- Snippets belonging to current_user within |clip| -->
          <% clip.clips.each do |snippet| %>
            <% if Clip.find(snippet.snippable_id).user_id == @user.id %>
              <div class="index_snippet snippet hoverable hide"><%= link_to snippet.title, clip_path(snippet.id) %></br>
                by: <%= clip.performer %></br>
                <audio id="track" controls src="<%=snippet.mp3.url%>"></audio></br>
                <%= snippet.description %></br>
                <div id="clip<%= snippet.id %>" >
                  <button class="Like">Like</button></br>
                  Likes: <p><%=snippet.likes.count%></p>
                </div>
              </div>
            <% end %>
          <% end %>
          <!-- Link to show *all* snippets made from |clip| -->
            <div class="index_snippet hoverable hide">
          <a href="/clips/<%= clip.id %>/snippets">
              Click to view all snippets
          </a>
            </div>
        <% end %>

      </ol>
    <% end %>
<% end %>

<%= javascript_include_tag "users_show" %>
<%= javascript_include_tag "likes" %>