config/routes.rb
WdiGroupProject::Application.routes.draw do

  devise_for :users
  resources :users
  root to: "clips#index"

  resources :clips, except: [:update, :edit] do
    resources :comments#, except: [:index, :show]
  end

  post '/clips/update/:id', to: 'clips#like_clicked'
  patch '/clips/:clip_id/playlist/:id', to: 'clips#add_to_playlist'
  post '/clips/playlist/:id', to: 'clips#add_playlist'
  get '/map', to: 'clips#map_clips'


  post '/search', to: 'search#create'

  post '/clips/:id', to: 'clips#snippet'
  get '/clips/:id/snippets', to: 'clips#snippets'

  resources :playlists



end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :clip_playlists
  has_many :clips, through: :clip_playlists
  accepts_nested_attributes_for :clips
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = current_user.playlists
    @playlist = Playlist.new
  end

  def new
    @playlist = Playlist.new
  end

  def create
    playlist = current_user.playlists
      .create(params.require(:playlist).permit(:title))

    redirect_to playlists_path
  end

  def edit
  end


  def show
    @playlist = Playlist.find(params[:id])
  end

  def destroy
  end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_playlist.html.erb
<div class="clip">
  <% unless current_user == nil %>
    <div class="btn-group" id="clip<%=params[:id]%>">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
       add to playlist <span class="caret"></span>
     </button>
     <ul class="dropdown-menu" role="menu">
       <% unless current_user.playlists == nil %>
         <% current_user.playlists.each do |p| %>
           <li id="playlist<%=p.id %>" class="playlist" >
             <%=p.title%>
              <% if @clip.playlists.exists?(id: p.id)%>
                <span class="glyphicon glyphicon-ok"></span>
              <% else %>
                <span></span>
              <% end %>
            <li>
          <% end %>
        <% end %>
        <%= form_tag '/playlists', method: 'post' do %>
            <%= text_field_tag :playlist[:title], :placeholder => 'new playlist' %>
            <%= submit_tag %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

app/views/playlists/index.html.erb
<div class = index>
  <center><h1><%= current_user.email %>'s playlists</h1></center>
</div>

<div class="index">
    <%= form_for @playlist do |f| %>
  <%= f.text_field :title, placeholder: "new playlist title", class: "form-control" %>
  <%= f.submit "create playlist", class: "btn btn-default" %>
<% end %>
</div>

<% unless @playlists == [] %>
  <ul class = "search_block playlist_index">
    <% @playlists.each do |p| %>
      <li><%= link_to p.title, playlist_path(p) %></li>
    <% end %>
  <ul>
<% end %>

app/views/playlists/new.html.erb
<h1> new playlist </h1>

<%= form_for @playlist do |f| %>
  <%= f.text_field :title, placeholder: :title %>
  <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<h1 class="index"><center><%= @playlist.title%> <center></h1>
<% unless @playlist.clips == [] %>
  <div class="search_block">
    <% @playlist.clips.each do |c| %>
      <div class="search_result">
        <h3><%= link_to c.title, clip_path(c) %></h3>
        <%= c.display_tags %><br>
        <audio id="ott" controls src="<%=c.mp3.url%>"><br>
      </div>
    <% end %>
  </div>
<% end %>